apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  selector:
    matchLabels:
      app: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - image: mysql:5.6
        name: user-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_PASSWORD
          value: Test12345
        - name: MYSQL_DATABASE
          value: user_ms_test
        ports:
        - containerPort: 3306
          name: user-db
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  type: NodePort
  ports:
  - port: 3307
    nodePort: 30003
    targetPort: 3306
  selector:
    app: user-db