apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: fragg90/user_service:1.1.0
        name: user-service
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://user-db:3307/user_ms_test?characterEncoding=utf8&serverTimezone=CET&createDatabaseIfNotExist=true
        - name: spring.datasource.username
          value: root
        - name: spring.datasource.password
          value: root
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8762/eureka
        ports:
        - containerPort: 8066
          name: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
  - port: 3317
    nodePort: 30002
    targetPort: 8068
  selector:
    app: user-service